name: 'Run integration tests'
description: 'Run the integration tests for a given Python version. These tests come from the cord-backend.'

BACKEND_REPO: cord-team/cord-backend
PROJECT: sdk-integration-tests
TEST_DIR: ./src/cord/sdk_integration_tests/tests
ENVIRONMENT: DEV

inputs:
  python-version:
    description: 'Python version to use'
    default: 3.7.12
    required: false
  poetry-version:
    description: 'Poetry version to use'
    default: 1.1.12
    required: false
  test-report-file:
    description: 'File name to save the test report in'
    required: true
  private-key:
    description: 'Private key for integration tests'
    required: true
  backend-access-token:
    description: 'Access token to backend repo'
    required: true

runs:
  using: "composite"

  steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout backend repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.BACKEND_REPO }}
          token: ${{ inputs.backend-access-token }}

      - name: Setup Poetry environment
        uses: ./.github/actions/setup-poetry-environment
        with:
          project: ${{ env.PROJECT }}
          cache-key: sdk-${{ hashFiles('projects/sdk-integration-tests/poetry.lock') }}-1

      - name: Setup FFMPEG
        uses: FedericoCarboni/setup-ffmpeg@v1

      - name: Get SDK
        run: |
          cd projects/${{ env.PROJECT }}
          python -m pip install --upgrade pip
          GIT_REPO=${{ github.repositoryUrl }}
          poetry add git+"${GIT_REPO/"git:"/"https:"}"
          poetry install
        shell: bash

      - name: Run tests
        run: |
          cd projects/${{ env.PROJECT }}
          source .venv/bin/activate
          export CORD_ENV=${{ env.ENVIRONMENT }}
          export PRIVATE_KEY="${{ inputs.private-key }}"
          python -m pytest ${{ env.TEST_DIR }} --rootdir=${{ env.TEST_DIR }} --verbose --junitxml=${{ env.SDK_TEST_REPORT }}
        shell: bash

      - name: Upload report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ env.SDK_TEST_REPORT }}
          path: projects/${{ env.PROJECT }}/${{ env.SDK_TEST_REPORT }}
